version: "3"


services:
  operator:
    image: gcr.io/openoracle-de73b/operator:latest 
    volumes:
      - ./:/open-oracle/
    working_dir: /open-oracle
    command: --config config-files/operator-docker-compose.yaml --operator-address 0x860B6912C2d0337ef05bbC89b0C2CB6CbAEAB4A5 --bls-private-key keys/bls_key/keys/1.bls.key.json --ecdsa-private-key keys/ecdsa_key/keys/1.ecdsa.key.json


